### ISSUE TITLE
investigate clientside caching

### ISSUE THREAD

**Issue by jgravois** [jgravois/lerc-leaflet#1]
Esri/lerc#9

**Comment by lucianpls** [comment]
Turns out it is working fine most of the time.  The exception was the slider, since the layer.redraw() is forcing a tileset refresh.  Instead, the slider should just draw each tile, which reuses the decoded data.
This is the pattern that any browser side app should follow.

**Comment by jgravois** [comment]
:+1: thanks for the refactor in ae68c580b9ea5617899b0faba52ae7a431ddddab
