### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by lucianpls** [jgravois/lerc-leaflet#6]
It's not working when checked out.  In FireFox the error is "L is not defined".
Please fix!

**Comment by jgravois** [comment]
are you trying to load the sample in the browser via `file:///` protocol?

`http` is recommended, but i just tweaked the sample to explicitly load script tags via `https` to make the sample a little more bulletproof.

21d8f26c326a23b14f61b6269727485ca63604e5

looking forward to hearing whether that sorts you out.  if not, more info would be appreciated.

**Comment by lucianpls** [comment]
Yes indeed, that was the problem.  Sure makes it annoying to develop, as it needs a server.

**Comment by jgravois** [comment]
Python's `SimpleHTTPServer` and node's `http-server` are both good lightweight options.
https://gist.github.com/jgravois/5e73b56fa7756fd00b89
